config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self) rescue ActiveAdmin::DatabaseHitDuringLoad
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#index'
  resources :static_pages do
    collection do
      get   'about_us'
      get   'vision'
      get   'brief_report'
    end
  end
  match '/home',   to: 'static_pages#index',   via: 'get'
  match '/about_us',   to: 'static_pages#about_us',   via: 'get'
  match '/vision',   to: 'static_pages#vision',   via: 'get'
  match '/brief_report',   to: 'static_pages#brief_report',   via: 'get'
  match '/bullet_board',   to: 'static_pages#bullet_board',   via: 'get'
  match '/bulletin/:id',   to: 'static_pages#bulletin',   via: 'get',   as: 'post'
  match '/photo_gallery',   to: 'static_pages#photo_gallery',   via: 'get'
  match '/',   to: 'static_pages#create',   via: 'post'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  # 1 = Bulletin
  # 2 = Provincial Education Advisors Message
  # 3 = Photo Gallery
  # 4 = Short Posts
  # 5 = About Us
  # 6 = Vision & Mission
  # 7 = Report
  has_many_attached :image_attachment
  has_many_attached :file_attachment

  def self.get_choices
   setting = Setting.first
   return [[1, setting.menu_2], [2, setting.advisor_message], [3, setting.section_1], [5, setting.menu_3], [6, setting.menu_4], [7, setting.menu_5]]
  end


  def self.bulletins
    Post.where(section_id: 1).order("created_at DESC")
  end

  def self.pinned_post
    Post.where(section_id: 1, is_pinned: true).order("created_at DESC")
  end

  def self.latest_post
    Post.where(section_id: 1, is_pinned: false).order("created_at DESC")
  end

  def self.advisor_message
    Post.where(section_id: 2).last
  end

  def self.photo_galleries
    Post.where(section_id: 3).order("created_at DESC")
  end

  def self.short_posts
    Post.where(section_id: 4).order("created_at DESC")
  end

  def self.about_us
    Post.where(section_id: 5).last
  end

  def self.vision_and_mission
    Post.where(section_id: 6).last
  end

  def self.brief_report
    Post.where(section_id: 7).last
  end
end

app/models/setting.rb
class Setting < ApplicationRecord
  has_one_attached :logo_attachment
  has_one_attached :background_attachment
  has_one_attached :image_attachment
  DEFAULTS = {
    "title" => "East Sepik Province",
    "description" => "The province is located on the north of Papua New Guinea and the provincial capital is Wewak. The province has six electorates with political representatives to the National Parliament.",
    "menu_1" => "Home",
    "menu_2" => "Bulletin",
    "menu_3" => "About Us",
    "menu_4" => "Mission & Vision",
    "menu_5" => "Report",
    "advisor_message" => "Advisor Message",
    "section_1" => "Photo Gallery",
    "section_1_description" => "Photos of various events hosted by the East Sepik Province Division of Education.",
    "section_2" => "Get in Touch",
    "section_2_description" => "Tour function information without cross action media value quickly maximize timely deliverables.",
    "brief_introduction" => "The province is located on the north of Papua New Guinea and the provincial capital is Wewak. The province has six electorates with political representatives to the National Parliament.",
    "address" => "",
    "email_address" => "",
    "contact_number_1" => "",
    "contact_number_2" => ""
  }


  def self.get_settings_value(kval)
    # puts "working...."
    default_settings = Setting.first
    if default_settings
      if default_settings[kval]
          return default_settings[kval]
      end
    end

    return Setting::DEFAULTS[kval]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_settings


  def get_settings
    @setting = Setting.first
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @advisor_message = Post.advisor_message
  end

  def about_us
    @post = Post.about_us
  end

  def vision
    @post = Post.vision_and_mission
  end

  def brief_report
    @post = Post.brief_report
  end

  def bullet_board
  end

  def photo_gallery
  end

  def bulletin
    @post = Post.find(params[:id])
    render 'show_post'
  end

  skip_before_action :verify_authenticity_token
  def create
    UserMailer.with(name: params[:name], email: params[:email], phone_number: params[:phone_number], subject: params[:subject], message: params[:message]).send_contact.deliver_now
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def truncate_html_to_sentence(notes)
    if !notes.nil?
      truncate(ActionView::Base.full_sanitizer.sanitize(notes), length: 50, omission: '...')
    else
      ""
    end
  end

  def truncate_html_length_to_sentence(notes, char_length)
    if !notes.nil?
      truncate(ActionView::Base.full_sanitizer.sanitize(notes), length: char_length, omission: '...')
    else
      ""
    end
  end

end

app/helpers/settings_helper.rb
module SettingsHelper
  def get_title
    get_settings_value('title')
  end

  def get_description
    get_settings_value('description')
  end

  def get_menu_1
    get_settings_value('menu_1')
  end

  def get_menu_2
    get_settings_value('menu_2')
  end

  def get_menu_3
    get_settings_value('menu_3')
  end

  def get_menu_4
    get_settings_value('menu_4')
  end

  def get_menu_5
    get_settings_value('menu_5')
  end

  def get_advisor_message
    get_settings_value('advisor_message')
  end

  def get_section_1
    get_settings_value('section_1')
  end

  def get_section_1_description
    get_settings_value('section_1_description')
  end

  def get_section_2
    get_settings_value('section_2')
  end

  def get_section_2_description
    get_settings_value('section_2_description')
  end

  def get_address
    get_settings_value('address')
  end

  def get_email_address
    get_settings_value('email_address')
  end

  def get_contact_number_1
    get_settings_value('contact_number_1')
  end

  def get_contact_number_2
    get_settings_value('contact_number_2')
  end

  def get_settings_value(kval)
    if default_settings
      if default_settings[kval]
          return default_settings[kval]
      end
    end

    return Setting::DEFAULTS[kval]
  end

  def default_settings
    Setting.first
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title><%= get_title %> | Division of Education</title>
  <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta content="" name="description" />
  <meta content="" name="author" />

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" integrity="sha256-rByPlHULObEjJ6XQxW/flG2r+22R5dKiAoef+aXWfik=" crossorigin="anonymous"/>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- Add the slick-theme.css if you want default styling -->
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
  <!-- Add the slick-theme.css if you want default styling -->
  <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha512-+NqPlbbtM1QqiK8ZAo4Yrj2c4lNQoGv8P79DPtKzj++l5jnN39rHA/xsqn8zE9l0uSoxaCdrOgFs6yjyfbBxSg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/1.3.0/jquery-migrate.min.js" integrity="sha512-WRDB0crT0y8RlW/sPVeMq6+z+UM21gEvrvzXyAcojZEfQt+mGun7+ntGr9HCe3HHuFJspJbb5na4XKBzYCZvaA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js" integrity="sha512-uto9mlQzrs59VwILcLiRYeLKPPbS/bT71da/OEBYEwcdNUk8jYIy+D176RYoop1Da+f9mvkYrmj5MCLZWEtQuA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha512-U85Jq47KunKegjv6gVMAnQwtQjovdXz/DQOvQoxrD6j3aGfDDbp5AAJuOdnQx1sefM90D9KBKSQkZGR5hrLbtg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/holder/2.9.8/holder.min.js" integrity="sha512-O6R6IBONpEcZVYJAmSC+20vdsM07uFuGjFf0n/Zthm8sOFW+lAq/OK1WOL8vk93GBDxtMIy6ocbj6lduyeLuqQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <script>
      $(document).ready(function () {
          $('.responsive').slick({
              centerMode: true,
              centerPadding: '20px',
              slidesToShow: 1,
              responsive: [
                  {
                      breakpoint: 768,
                      settings: {
                          arrows: false,
                          centerMode: true,
                          centerPadding: '0',
                          slidesToShow: 1
                      }
                  },
                  {
                      breakpoint: 480,
                      settings: {
                          arrows: false,
                          centerMode: true,
                          centerPadding: '0',
                          slidesToShow: 1
                      }
                  }
              ]
          });
      });
  </script>
</head>

<body>
<% @setting = Setting.first %>
<% if !@setting.background_attachment.nil? %>
  <% if @setting.background_attachment.attached? %>
    <style>
        .breadcam_bg_2 {
            background-image: url('<%= rails_blob_url(@setting.background_attachment) %>');
        }
    </style>
  <% else %>
    <style>
        .breadcam_bg_2 {
            background: none
        }
    </style>
  <% end %>
<% else %>
  <style>
      .breadcam_bg_2 {
          background: none
      }
  </style>
<% end %>
<%= render 'layouts/static/header' %>
<%= yield %>
</body>
</html>

app/views/static_pages/_contact_us.html.erb
<div class="get_in_tauch_area" id="get_in_tauch_area" >
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="section_title text-center mb-30">
          <h3 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s"><%= get_section_2 %></h3>
          <p class="text-center wow fadeInUp" data-wow-duration="1s" data-wow-delay=".4s">
            <b><%= get_title %></b><br/>
            <i><%= "<i class='fas fa-map-marker-alt'></i> #{get_address}".html_safe if get_address %></i><br/>
            <%= "<i class='fas fa-envelope'></i> <a href='mailto:#{get_email_address}'>#{get_email_address}</a>".html_safe if get_email_address %><br/>
            <i><%= "<i class='fas fa-mobile'></i> #{get_contact_number_1}".html_safe if get_contact_number_1 %></i><br/>
            <i><%= "<i class='fas fa-phone'></i> #{get_contact_number_2}".html_safe if get_contact_number_2 %></i>
          </p>
        </div>
        <div class="dropdown-divider"></div>
      </div>
    </div>
    <div class="row justify-content-center mt-30">
      <div class="col-lg-8">
        <div class="touch_form">
          <form action="/" method="post">
            <div class="row">
              <div class="col-md-6">
                <div class="single_input wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
                  <input type="text" name="name" placeholder="Your Name" required>
                </div>
              </div>
              <div class="col-md-6">
                <div class="single_input wow fadeInUp" data-wow-duration="1s" data-wow-delay=".4s">
                  <input type="email" name="email" placeholder="Email" required>
                </div>
              </div>
              <div class="col-md-12">
                <div class="single_input wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">
                  <input type="text" name="phone_number" placeholder="Phone/Telephone Number" required>
                </div>
              </div>
              <div class="col-md-12">
                <div class="single_input wow fadeInUp" data-wow-duration="1s" data-wow-delay=".5s">
                  <input type="text" name="subject" placeholder="Subject" required>
                </div>
              </div>
              <div class="col-md-12">
                <div class="single_input wow fadeInUp" data-wow-duration="1s" data-wow-delay=".6s">
                  <textarea name="message" id="" cols="30" placeholder="Message" rows="10" required></textarea>
                </div>
              </div>
              <div class="col-lg-12">
                <div class="submit_btn wow fadeInUp" data-wow-duration="1s" data-wow-delay=".7s">
                  <button class="boxed-btn3" type="submit">Send Message</button>
                </div>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/_image_carousel.html.erb
<% image_size ||= 400 %>

<% if !post.image_attachment.nil?  %>
  <% if post.image_attachment.attached? %>
    <div class='text-center' style='max-width: <%= image_size %>px; margin: auto;'>
      <div class="responsive">
        <% post.image_attachment.each do |image_attachment| %>
          <div class="">
            <%= image_tag image_attachment, :class => 'img-fluid mx-auto', :style => 'width: 100%; max-width: 350px;', :alt => post.title %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/static_pages/_sidebar.html.erb
<div class="col-lg-4">
  <div class="blog_right_sidebar">
    <!--    <aside class="single_sidebar_widget search_widget">-->
    <!--      <form action="#">-->
    <!--        <div class="form-group">-->
    <!--          <div class="input-group mb-3">-->
    <!--            <input type="text" class="form-control" placeholder='Search Keyword'-->
    <!--                   onfocus="this.placeholder = ''" onblur="this.placeholder = 'Search Keyword'">-->
    <!--            <div class="input-group-append">-->
    <!--              <button class="btn" type="button"><i class="ti-search"></i></button>-->
    <!--            </div>-->
    <!--          </div>-->
    <!--        </div>-->
    <!--        <button class="button rounded-0 primary-bg text-white w-100 btn_1 boxed-btn"-->
    <!--                type="submit">Search</button>-->
    <!--      </form>-->
    <!--    </aside>-->
    <aside class="single_sidebar_widget popular_post_widget">
      <h3 class="widget_title">Recent Post</h3>
      <% Post.bulletins.limit(5).each do |post| %>
        <div class="media post_item">
          <div class="media-body">
            <a href="<%= post_path(:id => post.id) %>">
              <h3><%= post.title %></h3>
            </a>
            <p><%= post.created_at.strftime('%B %d, %Y') %></p>
          </div>
        </div>
      <% end %>
    </aside>
    <aside class="single_sidebar_widget popular_post_widget">
      <h3 class="widget_title">Old Post</h3>
      <% Post.bulletins.order("created_at ASC").limit(5).each do |post| %>
        <div class="media post_item">
          <div class="media-body">
            <a href="<%= post_path(:id => post.id) %>">
              <h3><%= post.title %></h3>
            </a>
            <p><%= post.created_at.strftime('%B %d, %Y') %></p>
          </div>
        </div>
      <% end %>
    </aside>

  </div>
</div>

app/views/static_pages/_testimonial_area.html.erb
<!-- testimonial_area  -->
<div class="testimonial_area " style="display:none;">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="testmonial_active owl-carousel">
          <% Post.short_posts.limit(10).each do |post| %>
            <div class="single_carousel">
              <div class="single_testmonial text-center">
                <p><%= post.description.nil? ? '' : truncate_html_to_sentence(post.description) %></p>
                <div class="testmonial_author">
                  <h3><%= post.title %></h3>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /testimonial_area  -->

app/views/static_pages/about_us.html.erb
<!-- portfolio_details_banner_start  -->
<div class="portfolio_details_banner">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="details_info ">
          <h3 class="wow fadeInDown" data-wow-duration="1s" data-wow-delay=".3s"><%= @post.title %></h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- portfolio_details_banner_end  -->

<div class="portfolio_details_wrap">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-10">
        <div class="banner wow fadeInUp text-center mt-5" data-wow-duration="1.5s" data-wow-delay=".3s">
          <% if !@post.image_attachment.nil? %>
            <% if @post.image_attachment.attached? %>
              <%= image_tag @post.image_attachment[0], :class => 'img-fluid', :style => 'width: 50%;', :alt => @post.title %>
            <% else %>
              <div style="height: 80px;">&nbsp;</div>
            <% end %>
          <% else %>
            <div style="height: 80px;">&nbsp;</div>
          <% end %>
        </div>
        <div class="details_text">
          <div class="row">
            <div class="col-lg-12 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
              <%= @post.description.present? ? @post.description.html_safe : '' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<%= render 'static_pages/testimonial_area' %>

<%= render 'static_pages/contact_us' %>

<%= render 'layouts/static/footer' %>

app/views/static_pages/bullet_board.html.erb
<!-- bradcam_area  -->
<div class="bradcam_area breadcam_bg_2">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3><%= get_menu_2 %></h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /bradcam_area  -->
<!-- service_area  -->
<div class="service_area">
  <div class="container">
    <div class="row">
      <% Post.bulletins.limit(20).each do |post| %>
        <div class="col-xl-12 col-md-12">
          <div class="single_service wow fadeInLeft" data-wow-duration="1.2s" data-wow-delay=".4s">
            <div class="text-center">
              <h3><%= post.title %></h3>
              <% if !post.image_attachment.nil? %>
                <% if post.image_attachment.attached? %>
                  <%= image_tag post.image_attachment[0], :class => 'img-fluid', :style => 'width: 100%; max-width: 250px;', :alt => post.title %>
                <% end %>
              <% end %>
            </div>
            <p><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 250)}".html_safe : '' %></p>
            <div class="text-center">
              <a href="<%= post_path(:id => post.id) %>" class="boxed-btn3 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".7s">Read more...</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--/ service_area  -->

<%= render 'static_pages/testimonial_area' %>

<%= render 'static_pages/contact_us' %>

<%= render 'layouts/static/footer' %>

app/views/static_pages/index.html.erb
<% if !@advisor_message.image_attachment.nil? %>
  <% if @advisor_message.image_attachment.attached? %>
    <style>
        .about_area::before {
            background-image: url('<%= rails_blob_url(@advisor_message.image_attachment[0]) %>');
        }
    </style>
  <% else %>
    <style>
        .about_area::before {
            background: white
        }
    </style>
  <% end %>
<% else %>
  <style>
      .about_area::before {
          background: white
      }
  </style>
<% end %>

<%= render 'layouts/static/bradcam' %>

<!-- service_area  -->
<div class="service_area">
  <div class="container">
    <div class="row">
      <% Post.pinned_post.limit(3).each do |post| %>
        <div class="col-xl-12 col-md-12" style="margin-top: 1.5rem; margin-bottom: 1.5rem;">
          <div class="wow fadeInLeft" data-wow-duration="1.2s" data-wow-delay=".4s">
            <div class="text-center">
              <h3><%= post.title %></h3>
              <%= render partial: 'image_carousel', locals: { post: post } %>
            </div>
            <p><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 150)}".html_safe : '' %></p>
            <div class="text-center">
              <a href="<%= post_path(:id => post.id) %>" class="boxed-btn3 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".7s">Read
                more...</a>
            </div>
          </div>
        </div>
      <% end %>
      <% Post.latest_post.limit(3).each do |post| %>
        <div class="col-xl-4 col-md-4 my-2">
          <div class="single_service wow fadeInLeft" data-wow-duration="1.2s" data-wow-delay=".4s">
            <div class="text-center ">
              <% if !post.image_attachment.nil? %>
                <% if post.image_attachment.attached? %>
                  <%= image_tag post.image_attachment[0], :class => 'img-fluid', :style => 'width: 50%;', :alt => post.title %>
                <% end %>
              <% end %>
            </div>
            <h3><%= post.title %></h3>
            <p><%= post.description.present? ? truncate_html_length_to_sentence(post.description, 150) : '' %></p>
            <div class="text-center ">
            <a href="<%= post_path(:id => post.id) %>" class="boxed-btn3 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".7s">Read
              more...</a>
          </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <div class="col-xl-12 col-md-12 my-2">
        <div class="text-center wow fadeInLeft" data-wow-duration="1.2s" data-wow-delay=".4s">
          <a href="<%= bullet_board_path %>" class="boxed-btn3 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".7s">Click
            for more updates</a>
        </div>
      </div>
    </div>
  </div>
</div>
<!--/ service_area  -->

<div class="about_area">
  <div class="container">
    <div class="row justify-content-end">
      <div class="col-lg-5 offset-lg-1">
        <div class="about_info">
          <div class="section_title white_text">
            <h3 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".4s"><%= @advisor_message.title %></h3>
            <p class="last_text wow fadeInUp" data-wow-duration="1s" data-wow-delay=".6s"><%= @advisor_message.description.present? ? @advisor_message.description.html_safe : '' %></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- portfolio_image_area  -->
<div class="portfolio_image_area">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-6">
        <div class="section_title text-center mb-90">
          <h3 class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s"><%= get_section_1 %></h3>
          <p class="wow fadeInUp" data-wow-duration="1s" data-wow-delay=".4s"><%= get_section_1_description %></p>
        </div>
      </div>
    </div>
    <div class="row">
      <% Post.photo_galleries.limit(12).each do |post| %>
        <div class="col-lg-6 col-md-12">
          <div class="single_Portfolio wow fadeInUp" data-wow-duration="1s" data-wow-delay=".3s">
            <div class="portfolio_thumb">
              <% if !post.image_attachment.nil? %>
                <% if post.image_attachment.attached? %>
                  <%= image_tag post.image_attachment[0], :alt => post.title %>
                <% end %>
              <% end %>
            </div>
            <div class="portfolio_hover">
              <div class="title">
                <a href="<%= post_path(:id => post.id) %>">
                  <span><%= post.title %></span>
                  <h3><%= post.description.present? ? '' : truncate_html_to_sentence(post.description) %></h3>
                </a>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--/ portfolio_image_area  -->


<%= render 'static_pages/testimonial_area' %>

<%= render 'static_pages/contact_us' %>

<%= render 'layouts/static/footer' %>

app/views/static_pages/photo_gallery.html.erb
<!-- bradcam_area  -->
<div class="bradcam_area breadcam_bg_2">
  <div class="container">
    <div class="row">
      <div class="col-xl-12">
        <div class="bradcam_text">
          <h3><%= get_section_1 %></h3>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- /bradcam_area  -->
<!-- service_area  -->
<div class="service_area">
  <div class="container">
    <div class="row">
      <% Post.photo_galleries.each do |post| %>
        <div class="col-xl-12 col-md-12">
          <div class="single_service text-center wow fadeInLeft" data-wow-duration="1.2s" data-wow-delay=".4s">
            <h3><%= post.title %></h3>
            <% if !post.image_attachment.nil? %>
              <% if post.image_attachment.attached? %>
                <%= image_tag post.image_attachment[0], :class => 'img-fluid', :style => 'width: 100%; max-width: 250px;', :alt => post.title %>
              <% end %>
            <% end %>
            <p><%= post.description.present? ? "#{truncate_html_length_to_sentence(post.description, 1000)}".html_safe : '' %></p>
            <a href="<%= post_path(:id => post.id) %>" class="boxed-btn3 wow fadeInUp" data-wow-duration="1s" data-wow-delay=".7s">See
              more...</a>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<!--/ service_area  -->

<%= render 'static_pages/testimonial_area' %>

<%= render 'static_pages/contact_us' %>

<%= render 'layouts/static/footer' %>